name: Build Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-macos:
    runs-on: macos-11
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Compile
        run: make -f macos.mk

      - name: Prepare output
        run: |
          zip include.zip *.h pffft_double/pffft_double.h *.inc
          mv libr8brain.a libr8brain-macos11.a

      - name: Upload build output
        uses: actions/upload-artifact@v2
        with:
          name: build-output-macos11
          path: |
            include.zip
            libr8brain-macos11.a
            LICENSE

  build-macos-arm64:
    runs-on: [self-hosted, macOS, ARM64]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Compile
        run: make -f macos.mk

      - name: Prepare output
        run: mv libr8brain.a libr8brain-macos-arm64.a

      - name: Upload build output
        uses: actions/upload-artifact@v2
        with:
          name: build-output-macos-arm64
          path: libr8brain-macos-arm64.a

  build-linux:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Get RPi toolchain
        run: |
          wget https://github.com/sfjohnson/rpi-toolchain/releases/download/v0.0.6/arm-rpi-linux-gnueabihf.tar.xz
          tar xf arm-rpi-linux-gnueabihf.tar.xz -C ~

      - name: Compile
        run: |
          make -f android30.mk
          make -f android30.mk clean
          make -f rpi.mk
          make -f rpi.mk clean
          make -f linux-x64.mk

      - name: Upload build output
        uses: actions/upload-artifact@v2
        with:
          name: build-output-linux
          path: |
            libr8brain-android30.a
            libr8brain-rpi.a
            libr8brain-linux-x64.a

  create-release:
    runs-on: ubuntu-22.04
    needs: [build-macos, build-linux, build-macos-arm64]
    steps:
      - name: Get build output macos11
        uses: actions/download-artifact@v2
        with:
          name: build-output-macos11

      - name: Get build output linux
        uses: actions/download-artifact@v2
        with:
          name: build-output-linux

      - name: Get build output macos-arm64
        uses: actions/download-artifact@v2
        with:
          name: build-output-macos-arm64

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            include.zip
            libr8brain-macos11.a
            libr8brain-android30.a
            libr8brain-macos-arm64.a
            libr8brain-rpi.a
            libr8brain-linux-x64.a
            LICENSE
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
