name: Build Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-macos:
    runs-on: macos-12
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Compile
        run: make -f macos.mk

      - name: Prepare output
        run: |
          zip include.zip *.h pffft_double/pffft_double.h *.inc
          mv libr8brain.a libr8brain-macos12.a

      - name: Upload build output
        uses: actions/upload-artifact@v4
        with:
          name: build-output-macos12
          path: |
            include.zip
            libr8brain-macos12.a
            LICENSE

  build-macos-arm64:
    runs-on: macos-14
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Compile
        run: make -f macos.mk

      - name: Prepare output
        run: mv libr8brain.a libr8brain-macos-arm64.a

      - name: Upload build output
        uses: actions/upload-artifact@v4
        with:
          name: build-output-macos-arm64
          path: libr8brain-macos-arm64.a

  build-linux:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Get RPi toolchain
        run: |
          wget https://github.com/sfjohnson/rpi-toolchain/releases/download/v0.1.8/aarch64-rpi4-linux-gnu.tar.xz
          tar xf aarch64-rpi4-linux-gnu.tar.xz -C ~

      - name: Compile
        run: |
          make -f rpi-arm64.mk
          make -f rpi-arm64.mk clean
          make -f linux-x64.mk

      - name: Upload build output
        uses: actions/upload-artifact@v4
        with:
          name: build-output-linux
          path: |
            libr8brain-rpi-arm64.a
            libr8brain-linux-x64.a

  create-release:
    runs-on: ubuntu-22.04
    needs: [build-macos, build-linux, build-macos-arm64]
    steps:
      - name: Get build output macos12
        uses: actions/download-artifact@v4
        with:
          name: build-output-macos12

      - name: Get build output linux
        uses: actions/download-artifact@v4
        with:
          name: build-output-linux

      - name: Get build output macos-arm64
        uses: actions/download-artifact@v4
        with:
          name: build-output-macos-arm64

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            include.zip
            libr8brain-macos12.a
            libr8brain-macos-arm64.a
            libr8brain-rpi-arm64.a
            libr8brain-linux-x64.a
            LICENSE
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
